export const productsData=[
    {id: "1", nombre:"Amarila", tipo:"producto", categoria:"mandalas", precio: 600, img:"../media/amarilla.jpeg"},
    {id: "2", nombre:"Colores", tipo:"producto", categoria:"unicos", precio: 650, img:"../media/portavelaColores.jpeg"},
    {id: "3", nombre:"Olla de Barro Lisa", tipo:"producto", categoria:"vajillas", precio: 2500, img:"../media/olla de barro lisa.jpg"},
    {id: "4", nombre:"Bella", tipo:"producto", categoria:"mandalas", precio: 600, img:"../media/bella.jpeg"},
    {id: "5", nombre:"Cuadrado", tipo:"producto", categoria:"unicos", precio: 650, img:"../media/portavelaCuadrado.jpeg"},
    {id: "6", nombre:"Bandejas Floreadas", tipo:"producto", categoria:"vajillas", precio: 2300, img:"../media/bandejas floreadas.jpg"},
    {id: "7", nombre:"Celeste", tipo:"producto", categoria:"mandalas", precio: 600, img:"../media/Celeste.jpeg"},
    {id: "8", nombre:"Coral Chico", tipo:"producto", categoria:"unicos", precio: 600, img:"../media/portavelasCoralChico.jpeg"},
    {id: "9", nombre:"Platos Floreados", tipo:"producto", categoria:"vajillas", precio: 700, img:"../media/platos.jpg"},
    {id: "10", nombre:"Lila", tipo:"producto", categoria:"mandalas", precio: 600, img:"../media/lila.jpeg"},
    {id: "11", nombre:"Caramelera Amarilla", tipo:"producto", categoria:"unicos", precio: 900, img:"../media/calamereraAmarilla.jpeg"},
    {id: "12", nombre:"Bandejas Hojas ", tipo:"producto", categoria:"vajillas", precio: 500, img:"../media/bandejahojas.jpg"},
    {id: "13", nombre:"Verde Manzana", tipo:"producto", categoria:"mandalas", precio: 600, img:"../media/verdeManzana.jpeg"},
    {id: "14", nombre:"Caramelera Colores", tipo:"producto", categoria:"unicos", precio: 900, img:"../media/calamereraColores.jpeg"},
    {id: "15", nombre:"El Pajarito", tipo:"producto", categoria:"vajillas", precio: 500, img:"../media/bandejapajarito.jpg"},
    {id: "16", nombre:"Turquesa", tipo:"producto", categoria:"mandalas", precio: 600, img:"../media/turquesa.jpeg"},
    {id: "17", nombre:"Triangulos", tipo:"producto", categoria:"unicos", precio: 1000, img:"../media/tarroTriangulos.jpeg"},
    {id: "18", nombre:"Juego Amarillo", tipo:"producto", categoria:"vajillas", precio: 2900, img:"../media/juegoteamarillo.jpg"},
    {id: "19", nombre:"Orange", tipo:"producto", categoria:"mandalas", precio: 600, img:"../media/orange.jpeg"},
    {id: "20", nombre:"Cuadrado", tipo:"producto", categoria:"unicos", precio: 650, img:"../media/portavelaCuadrado.jpeg"},
    {id: "21", nombre:"Set Rustico de Salsera y Quesera", tipo:"producto", categoria:"vajillas", precio: 2500, img:"../media/set rustico qys.jpg"},
    {id: "22", nombre:"Liz", tipo:"producto", categoria:"mandalas", precio: 600, img:"../media/liz.jpeg"},
    {id: "23", nombre:"Flores", tipo:"producto", categoria:"unicos", precio: 1000, img:"../media/tarroFlores.jpeg"},
    {id: "24", nombre:"Los Seis", tipo:"producto", categoria:"vajillas", precio: 2550, img:"../media/juegoseisamararillo.jpg"},
    {id: "25", nombre:"Corazón", tipo:"producto", categoria:"mandalas", precio: 600, img:"../media/corazon.jpeg"},
    {id: "26", nombre:"Medianos", tipo:"producto", categoria:"unicos", precio: 900, img:"../media/tarrosMedianos.jpeg"},
    {id: "27", nombre:"Los Cuatro", tipo:"producto", categoria:"vajillas", precio: 1500, img:"../media/losCuatro.jpg"},
    {id: "28", nombre:"Pastel", tipo:"producto", categoria:"mandalas", precio: 600, img:"../media/pastel.jpeg"},
    {id: "29", nombre:"Set Tazas y Lechera", tipo:"producto", categoria:"vajillas", precio: 1700, img:"../media/juegotazasylechera.jpeg"},
    {id: "30", nombre:"Limón", tipo:"producto", categoria:"mandalas", precio: 600, img:"../media/limon.jpeg"},
    {id: "31", nombre:"Olla Esmaltada", tipo:"producto", categoria:"ofertas", precio: 1780, img:"../media/ollaEsmaltada.jpg"},
    {id: "32", nombre:"Portavelas Verde Chico", tipo:"producto", categoria:"ofertas", precio: 450, img:"../media/portavelasVerdeChico.jpeg"},
    {id: "33", nombre:"Porta-Sahumerio", tipo:"producto", categoria:"ofertas", precio: 300, img:"../media/portasaumerios.jpeg"},
    {id: "34", nombre:"Juego Azul", tipo:"producto", categoria:"ofertas", precio: 2210, img:"../media/juegoAzul.jpg"},
    {id: "35", nombre:"Bucles", tipo:"producto", categoria:"ofertas", precio: 510, img:"../media/bucle.jpeg"},
    {id: "36", nombre:"Azucarera con Cuchara", tipo:"producto", categoria:"ofertas", precio: 850, img:"../media/azucareraconcuchara.jpeg"},
    {id: "37", nombre:"Juego Arena", tipo:"producto", categoria:"ofertas", precio: 1205, img:"../media/juegoArena.jpg"},
    {id: "38", nombre:"Flor", tipo:"producto", categoria:"ofertas", precio: 510, img:"../media/flor.jpeg"}
]